# Generated by Django 4.2.7 on 2023-12-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
