# Generated by Django 4.2.7 on 2024-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0008_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="unit",
            field=models.IntegerField(),
        ),
    ]
