# Generated by Django 4.2.7 on 2024-02-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0009_alter_ticket_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
